apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loadtest
  namespace: load-generator
spec:
  interval: 5m
  chart:
    spec:
      chart: app-chart
      sourceRef:
        kind: HelmRepository
        name: prog76-helm-repo
        namespace: flux-system
      version: 0.0.1
  values:
    metadata:
      name: loadtest
      project: loadtest
      instance: dev
      component: web
    image:
      repository:  docker.io/prog76/load-generator # {"$imagepolicy": "flux-system:load-generator:name"}
      tag: 1.0.1647230834 # {"$imagepolicy": "flux-system:load-generator:tag"}
    minReadySeconds: 10
    autoscale:
      enabled: true
      maxReplicas: 2
      minReplicas: 1
      targetCPUUtilizationPercentage: 60
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 3600
    env_map:
      foo: bar29
      WARMUP_DELAY: 50000
      SHUTDOWN_DELAY: 50000
      #      testsecret: "vault:secret/kubernetes/services/test/value.key"
      #    vault:
      #      enabled: true
    probes:
      startupProbe:
        httpGet:
          path: /warmup/
          port: 5000
        failureThreshold: 10
        timeoutSeconds: 10
        initialDelaySeconds: 5
      livenessProbe:
        httpGet:
          path: /status/
          port: 5000
        failureThreshold: 3
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /status/
          port: 5000
        failureThreshold: 3
        periodSeconds: 5
    service:
      enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
