apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-operator
  name: helm-operator
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http
  namespaceSelector:
    matchNames:
    - flux
  selector:
    matchLabels:
      app: helm-operator
      release: helm-operator
